# Generated by Django 4.1.3 on 2022-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
    ]
