# Generated by Django 4.1.3 on 2022-12-22 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverAdminGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(blank=True, max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriverModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50)),
                ('driver_last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=200, null=True)),
                ('salt', models.BinaryField(null=True)),
                ('password_hash', models.BinaryField(null=True)),
                ('admin_bool', models.BooleanField(default=False)),
                ('bot_user_id', models.CharField(blank=True, max_length=20, null=True)),
                ('drivers_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driveradmingroupmodel')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.AddField(
            model_name='driveradmingroupmodel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='drivers.drivermodel'),
        ),
    ]
