# Generated by Django 4.1.3 on 2022-11-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_drivermodel_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='password',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='drivermodel',
            name='salt',
            field=models.BinaryField(null=True),
        ),
    ]
