# Generated by Django 4.1.3 on 2022-11-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_alter_drivermodel_password_alter_drivermodel_salt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
