# Generated by Django 4.1.3 on 2022-11-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_drivermodel_password_hash_alter_drivermodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='bot_user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
