# Generated by Django 4.1.3 on 2022-11-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0006_drivermodel_bot_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermodel',
            name='bot_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
