# Generated by Django 4.1.3 on 2022-12-07 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_drivermodel_bot_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivermodel',
            name='admin_bool',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DriverAdminGroupModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='drivers.drivermodel')),
            ],
        ),
        migrations.AddField(
            model_name='drivermodel',
            name='drivers_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.driveradmingroupmodel'),
        ),
    ]
