# Generated by Django 4.1.3 on 2022-12-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0008_drivermodel_admin_bool_driveradmingroupmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driveradmingroupmodel',
            name='name_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='driveradmingroupmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
