# Generated by Django 4.1.3 on 2022-12-07 11:14

from django.db import migrations, models
import django.db.models.deletion
import drivers.models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0009_driveradmingroupmodel_name_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveradmingroupmodel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='drivers.drivermodel', validators=[drivers.models.admin_driver_validator]),
        ),
    ]
