# Generated by Django 4.1.3 on 2022-12-07 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0010_alter_driveradmingroupmodel_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driveradmingroupmodel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='drivers.drivermodel'),
        ),
    ]
