# Generated by Django 4.1.3 on 2022-12-22 09:39

from django.db import migrations, models
import excursions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionPointModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('photo', models.FileField(blank=True, null=True, upload_to=excursions.models.content_excursion_name)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Точка галереи',
                'verbose_name_plural': 'Точки галереи',
            },
        ),
        migrations.CreateModel(
            name='ExcursionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to=excursions.models.photo_file_name)),
                ('excursion_map', models.FileField(blank=True, null=True, upload_to=excursions.models.map_file_name)),
                ('custom', models.BooleanField(blank=True, default=False, null=True)),
                ('point', models.ManyToManyField(to='excursions.excursionpointmodel')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
            },
        ),
    ]
