# Generated by Django 4.1.3 on 2022-11-25 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0002_excursionphonecodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionphonecodmodel',
            name='excursions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionmodel'),
        ),
    ]
