# Generated by Django 4.1.3 on 2022-11-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0004_excursionpointmodel_excursionmodel_point'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionmodel',
            name='point',
        ),
        migrations.AddField(
            model_name='excursionpointmodel',
            name='excursions',
            field=models.ManyToManyField(to='excursions.excursionmodel'),
        ),
    ]
