# Generated by Django 4.1.3 on 2022-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0005_remove_excursionmodel_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionpointmodel',
            name='excursions',
        ),
        migrations.AddField(
            model_name='excursionmodel',
            name='point',
            field=models.ManyToManyField(to='excursions.excursionpointmodel'),
        ),
    ]
