# Generated by Django 4.1.3 on 2022-11-25 14:42

from django.db import migrations, models
import excursions.models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0006_remove_excursionpointmodel_excursions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionphonecodmodel',
            options={'verbose_name': 'Код для сверки', 'verbose_name_plural': 'Коды для сверки'},
        ),
        migrations.AlterModelOptions(
            name='excursionpointmodel',
            options={'verbose_name': 'Точка галереи', 'verbose_name_plural': 'Точки галереи'},
        ),
        migrations.AddField(
            model_name='excursionmodel',
            name='excursion_map',
            field=models.FileField(blank=True, null=True, upload_to=excursions.models.map_file_name),
        ),
    ]
