# Generated by Django 4.1.3 on 2022-11-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0007_alter_excursionphonecodmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionpointmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
