# Generated by Django 4.1.3 on 2022-12-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0008_excursionpointmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
