# Generated by Django 4.1.3 on 2022-12-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0009_alter_excursionmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionmodel',
            name='custom',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='excursionmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
