# Generated by Django 4.1.3 on 2022-12-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0010_excursionmodel_custom_alter_excursionmodel_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionphonecodmodel',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
