# Generated by Django 4.1.3 on 2022-12-13 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0011_alter_excursionphonecodmodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionphonecodmodel',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
