# Generated by Django 4.1.3 on 2022-12-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0012_alter_excursionphonecodmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionphonecodmodel',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
