# Generated by Django 4.1.3 on 2022-12-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0013_excursionphonecodmodel_custom_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionphonecodmodel',
            name='human_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
