# Generated by Django 4.1.3 on 2022-12-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0014_excursionphonecodmodel_human_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionphonecodmodel',
            name='human_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
