# Generated by Django 4.1.3 on 2022-12-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitemmodel',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
