# Generated by Django 4.1.3 on 2022-12-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartmodel_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='total_sum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
