# Generated by Django 4.1.3 on 2022-11-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0001_initial'),
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenexmodel',
            name='excursion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionmodel'),
        ),
    ]
