# Generated by Django 4.1.3 on 2022-11-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0007_alter_drivermodel_bot_user_id'),
        ('tokens', '0003_alter_tokenexmodel_driver_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenexmodel',
            name='driver_activate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drivers.drivermodel'),
        ),
    ]
