# Generated by Django 4.1.3 on 2022-12-14 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('excursions', '0013_excursionphonecodmodel_custom_price'),
        ('tokens', '0005_tokenexmodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenexmodel',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='excursions.excursionphonecodmodel'),
        ),
    ]
