# Generated by Django 4.1.3 on 2022-12-16 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0006_tokenexmodel_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenexmodel',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='tokenexmodel',
            name='excursion',
        ),
    ]
